# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Anila Devarashetty
#title: Senior Network System Administrator
email: devarashettyanila@gmail.com
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  Anila8707
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: Anila Devarashetty
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Anila here to pursue challenging and constant learning career and to work for the organization that gives the opportunity to apply my skills and knowledge.To each pinnacle in this field with hard work,dedication and leadership qualities.

  

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Designing Programming Language
        link: https://github.com/nnolas27/SER502-Spring2022-Team36
        # link_text: Project Website
        #additional_links:
         # - title:  sproogen/modern-resume-theme
          #  icon: fab fa-github
           # url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Programming Language Name: PLan (Programming-Language)
        description: | # this will include new lines to allow paragraphs
          Designed a programming language using ANTLR, Eclipse IDE, Java
  - title: Co-curricular Activities # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Online Project Management System.

        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Team Leader 
        caption: 2020 
        #quote: >
         # Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Worked as Team Leader for project “Online Project Management System using java.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Arizona State University
        caption: 2021 - 2023
        sub_title: Computer Software Engineering
        quote: >
          Established in 1885, ASU is a public research university in the Phoenix Metropolitan area, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at ASU I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          

  - title: Summary of skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      
      - Programming Languages: C, C++, Java
      - Web Technologies: HTML, CSS, Angular
      - Scripting - Python
      - Version Controlling - Git
      - Database Technologies - MYSQL, Mongo DB
      - Operating Systems - Windows

       

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
